/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto;

import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class newInterface2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(newInterface2.class.getName());

    /**
     * Creates new form newInterface2
     */
    public char sexo;
    public boolean astronomia, tecnologia, esportes;
    
    public newInterface2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp_Sexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        rdo_Masculino = new javax.swing.JRadioButton();
        rdo_Feminino = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        chk_Astronomia = new javax.swing.JCheckBox();
        chk_Tecnologia = new javax.swing.JCheckBox();
        chk_Esportes = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cmb_Idioma = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Sexo");

        btnGrp_Sexo.add(rdo_Masculino);
        rdo_Masculino.setText("Masculino");
        rdo_Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_MasculinoActionPerformed(evt);
            }
        });

        btnGrp_Sexo.add(rdo_Feminino);
        rdo_Feminino.setText("Feminino");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        chk_Astronomia.setText("Astronomia");

        chk_Tecnologia.setText("Tecnologia");
        chk_Tecnologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_TecnologiaActionPerformed(evt);
            }
        });

        chk_Esportes.setText("Esportes");

        jLabel3.setText("Curso");

        cmb_Idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espanhol", "Inglês", "Português" }));

        jLabel4.setText("Idioma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk_Tecnologia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk_Astronomia))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdo_Masculino)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdo_Feminino))
                                .addComponent(txtNome)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk_Esportes))
                    .addComponent(btnSalvar))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdo_Masculino)
                    .addComponent(rdo_Feminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_Tecnologia)
                    .addComponent(chk_Astronomia)
                    .addComponent(chk_Esportes)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_MasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_MasculinoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        tecnologia = chk_Tecnologia.isSelected();
        astronomia = chk_Astronomia.isSelected();
        esportes = chk_Esportes.isSelected();
        JOptionPane.showMessageDialog(null,"Tecnologia: "+tecnologia+
                "\nAstronomia: "+astronomia+
                "\nEsportes: "+esportes, "Alerta", JOptionPane.INFORMATION_MESSAGE);
        
        if(rdo_Masculino.isSelected()){
            sexo = 'M';
            JOptionPane.showMessageDialog(null, "Sexo masculino selecionado", "Alerta", JOptionPane.OK_OPTION);
            Pessoa p = new Pessoa(txtNome.getText(), sexo, String.valueOf(cmb_Idioma.getSelectedItem()));
        }
        else if(rdo_Feminino.isSelected()){
            sexo = 'F';
            JOptionPane.showMessageDialog(null, "Sexo feminino selecionado", "Alerta", JOptionPane.OK_OPTION);
             Pessoa p = new Pessoa(txtNome.getText(), sexo, String.valueOf(cmb_Idioma.getSelectedItem()));
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um sexo", "Erro", JOptionPane.ERROR);
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void chk_TecnologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_TecnologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_TecnologiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new newInterface2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrp_Sexo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chk_Astronomia;
    private javax.swing.JCheckBox chk_Esportes;
    private javax.swing.JCheckBox chk_Tecnologia;
    private javax.swing.JComboBox<String> cmb_Idioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rdo_Feminino;
    private javax.swing.JRadioButton rdo_Masculino;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
